// Code generator for Trust Wallet Core Go SDK
// Reads registry.json and generates type-safe coin wrappers
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// RegistryEntry represents a coin entry in registry.json
type RegistryEntry struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	CoinID      int    `json:"coinId"`
	Symbol      string `json:"symbol"`
	Decimals    int    `json:"decimals"`
	Blockchain  string `json:"blockchain"`
	Curve       string `json:"curve"`
	PublicKeyType string `json:"publicKeyType"`
}

// CoinTemplateData holds data for code generation
type CoinTemplateData struct {
	Coins          []RegistryEntry
	UniqueSymbolCoins []RegistryEntry
}

const coinTypesTemplate = `// Code generated by cmd/codegen. DO NOT EDIT.

package coin

// CoinType constants for all supported cryptocurrencies
const (
{{- range .Coins }}
	// {{ .Name }} ({{ .Symbol }})
	{{ .ID | Title }} CoinType = {{ .CoinID }}
{{- end }}
)

// AllCoins returns a slice of all supported coin types
func AllCoins() []CoinType {
	return []CoinType{
{{- range .Coins }}
		{{ .ID | Title }},
{{- end }}
	}
}

// CoinByID returns a CoinType by its string ID (e.g., "bitcoin", "ethereum")
func CoinByID(id string) (CoinType, bool) {
	switch id {
{{- range .Coins }}
	case "{{ .ID }}":
		return {{ .ID | Title }}, true
{{- end }}
	default:
		return 0, false
	}
}

// CoinBySymbol returns a CoinType by its symbol (e.g., "BTC", "ETH")
// Note: Some symbols map to multiple coins. Returns the first match.
func CoinBySymbol(symbol string) (CoinType, bool) {
	switch symbol {
{{- range .UniqueSymbolCoins }}
	case "{{ .Symbol }}":
		return {{ .ID | Title }}, true
{{- end }}
	default:
		return 0, false
	}
}
`

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <registry.json> <output-dir>\n", os.Args[0])
		os.Exit(1)
	}

	registryPath := os.Args[1]
	outputDir := os.Args[2]

	// Read registry.json
	data, err := os.ReadFile(registryPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading registry: %v\n", err)
		os.Exit(1)
	}

	var entries []RegistryEntry
	if err := json.Unmarshal(data, &entries); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing registry: %v\n", err)
		os.Exit(1)
	}

	// Filter entries with valid CoinID
	var coins []RegistryEntry
	for _, entry := range entries {
		if entry.CoinID >= 0 {
			coins = append(coins, entry)
		}
	}

	// Create unique symbol list (first occurrence wins)
	seenSymbols := make(map[string]bool)
	var uniqueSymbolCoins []RegistryEntry
	for _, coin := range coins {
		if !seenSymbols[coin.Symbol] {
			seenSymbols[coin.Symbol] = true
			uniqueSymbolCoins = append(uniqueSymbolCoins, coin)
		}
	}

	// Create template with helper functions
	funcMap := template.FuncMap{
		"Title": strings.Title,
	}

	tmpl, err := template.New("coins").Funcs(funcMap).Parse(coinTypesTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	// Generate coin types file
	outputPath := filepath.Join(outputDir, "coin_types_generated.go")
	f, err := os.Create(outputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintln(f, "//go:build cgo")
	fmt.Fprintln(f, "// +build cgo")
	fmt.Fprintln(f, "")

	if err := tmpl.Execute(f, CoinTemplateData{Coins: coins, UniqueSymbolCoins: uniqueSymbolCoins}); err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %d coin types in %s\n", len(coins), outputPath)
}
