//go:build !cgo
// +build !cgo

// Code generated by cmd/codegen. DO NOT EDIT.

package coin

// CoinType constants for all supported cryptocurrencies
const (
	// Bitcoin (BTC)
	Bitcoin CoinType = 0
	// Litecoin (LTC)
	Litecoin CoinType = 2
	// Dogecoin (DOGE)
	Dogecoin CoinType = 3
	// Ethereum (ETH)
	Ethereum CoinType = 60
	// Tron (TRX)
	Tron CoinType = 195
)

// AllCoins returns a slice of all supported coin types
func AllCoins() []CoinType {
	return []CoinType{Bitcoin, Litecoin, Dogecoin, Ethereum, Tron}
}

// CoinByID returns a CoinType by its string ID
func CoinByID(id string) (CoinType, bool) {
	switch id {
	case "bitcoin":
		return Bitcoin, true
	case "ethereum":
		return Ethereum, true
	case "dogecoin":
		return Dogecoin, true
	case "litecoin":
		return Litecoin, true
	case "tron":
		return Tron, true
	default:
		return 0, false
	}
}

// CoinBySymbol returns a CoinType by its symbol
func CoinBySymbol(symbol string) (CoinType, bool) {
	switch symbol {
	case "BTC":
		return Bitcoin, true
	case "ETH":
		return Ethereum, true
	case "DOGE":
		return Dogecoin, true
	case "LTC":
		return Litecoin, true
	case "TRX":
		return Tron, true
	default:
		return 0, false
	}
}
