//go:build cgo
// +build cgo

// Code generated by cmd/codegen. DO NOT EDIT.

package coin

// CoinType constants for all supported cryptocurrencies
const (
	// Bitcoin (BTC)
	Bitcoin CoinType = 0
	// Litecoin (LTC)
	Litecoin CoinType = 2
	// Dogecoin (DOGE)
	Doge CoinType = 3
	// Dash (DASH)
	Dash CoinType = 5
	// Viacoin (VIA)
	Viacoin CoinType = 14
	// Groestlcoin (GRS)
	Groestlcoin CoinType = 17
	// DigiByte (DGB)
	Digibyte CoinType = 20
	// Monacoin (MONA)
	Monacoin CoinType = 22
	// Decred (DCR)
	Decred CoinType = 42
	// Syscoin (SYS)
	Syscoin CoinType = 57
	// Base (ETH)
	Base CoinType = 8453
	// Linea (ETH)
	Linea CoinType = 59144
	// Mantle (MNT)
	Mantle CoinType = 5000
	// Zen EON (ZEN)
	Zeneon CoinType = 7332
	// Ethereum (ETH)
	Ethereum CoinType = 60
	// Ethereum Classic (ETC)
	Classic CoinType = 61
	// ICON (ICX)
	Icon CoinType = 74
	// Verge (XVG)
	Verge CoinType = 77
	// Pivx (PIVX)
	Pivx CoinType = 119
	// Zen (ZEN)
	Zen CoinType = 121
	// Aptos (APT)
	Aptos CoinType = 637
	// Sui (SUI)
	Sui CoinType = 784
	// Cosmos (ATOM)
	Cosmos CoinType = 118
	// Stargaze (STARS)
	Stargaze CoinType = 20000118
	// Juno (JUNO)
	Juno CoinType = 30000118
	// Stride (STRD)
	Stride CoinType = 40000118
	// Axelar (AXL)
	Axelar CoinType = 50000118
	// Crescent (CRE)
	Crescent CoinType = 60000118
	// Kujira (KUJI)
	Kujira CoinType = 70000118
	// Comdex (CMDX)
	Comdex CoinType = 80000118
	// Neutron (NTRN)
	Neutron CoinType = 90000118
	// Sommelier (SOMM)
	Sommelier CoinType = 11000118
	// FetchAI (FET)
	Fetchai CoinType = 12000118
	// Mars (MARS)
	Mars CoinType = 13000118
	// Umee (UMEE)
	Umee CoinType = 14000118
	// Noble (USDC)
	Noble CoinType = 18000118
	// Sei (SEI)
	Sei CoinType = 19000118
	// Tia (TIA)
	Tia CoinType = 21000118
	// Coreum (CORE)
	Coreum CoinType = 10000990
	// Quasar (QSR)
	Quasar CoinType = 15000118
	// Persistence (XPRT)
	Persistence CoinType = 16000118
	// Akash (AKT)
	Akash CoinType = 17000118
	// Zcash (ZEC)
	Zcash CoinType = 133
	// Firo (FIRO)
	Firo CoinType = 136
	// Komodo (KMD)
	Komodo CoinType = 141
	// XRP (XRP)
	Ripple CoinType = 144
	// Bitcoin Cash (BCH)
	Bitcoincash CoinType = 145
	// Stellar (XLM)
	Stellar CoinType = 148
	// Bitcoin Gold (BTG)
	Bitcoingold CoinType = 156
	// Nano (XNO)
	Nano CoinType = 165
	// Ravencoin (RVN)
	Ravencoin CoinType = 175
	// POA Network (POA)
	Poa CoinType = 178
	// EOS (EOS)
	Eos CoinType = 194
	// WAX (WAXP)
	Wax CoinType = 14001
	// Tron (TRX)
	Tron CoinType = 195
	// FIO (FIO)
	Fio CoinType = 235
	// Nimiq (NIM)
	Nimiq CoinType = 242
	// Algorand (ALGO)
	Algorand CoinType = 283
	// IoTeX (IOTX)
	Iotex CoinType = 304
	// IoTeX EVM (IOTX)
	Iotexevm CoinType = 10004689
	// Nervos (CKB)
	Nervos CoinType = 309
	// Zilliqa (ZIL)
	Zilliqa CoinType = 313
	// Terra (LUNC)
	Terra CoinType = 330
	// TerraV2 (LUNA)
	Terrav2 CoinType = 10000330
	// Polkadot (DOT)
	Polkadot CoinType = 354
	// Everscale (EVER)
	Everscale CoinType = 396
	// NEAR (NEAR)
	Near CoinType = 397
	// Aion (AION)
	Aion CoinType = 425
	// Kusama (KSM)
	Kusama CoinType = 434
	// Acala (ACA)
	Acala CoinType = 787
	// Acala EVM (ACA)
	Acalaevm CoinType = 10000787
	// Aeternity (AE)
	Aeternity CoinType = 457
	// Kava (KAVA)
	Kava CoinType = 459
	// Filecoin (FIL)
	Filecoin CoinType = 461
	// Bluzelle (BLZ)
	Bluzelle CoinType = 483
	// BandChain (BAND)
	Band CoinType = 494
	// Theta (THETA)
	Theta CoinType = 500
	// Theta Fuel (TFUEL)
	Tfuelevm CoinType = 361
	// Solana (SOL)
	Solana CoinType = 501
	// MultiversX (eGLD)
	Elrond CoinType = 508
	// Binance (BNB)
	Binance CoinType = 714
	// TBinance (BNB)
	Tbinance CoinType = 30000714
	// VeChain (VET)
	Vechain CoinType = 818
	// Callisto (CLO)
	Callisto CoinType = 820
	// NEO (NEO)
	Neo CoinType = 888
	// Viction (VIC)
	Viction CoinType = 889
	// Bitcoin Diamond (BCD)
	Bitcoindiamond CoinType = 999
	// ThunderCore (TT)
	Thundertoken CoinType = 1001
	// Harmony (ONE)
	Harmony CoinType = 1023
	// Oasis (ROSE)
	Oasis CoinType = 474
	// Ontology (ONT)
	Ontology CoinType = 1024
	// Tezos (XTZ)
	Tezos CoinType = 1729
	// Cardano (ADA)
	Cardano CoinType = 1815
	// Kin (KIN)
	Kin CoinType = 2017
	// Qtum (QTUM)
	Qtum CoinType = 2301
	// Nebulas (NAS)
	Nebulas CoinType = 2718
	// GoChain (GO)
	Gochain CoinType = 6060
	// NULS (NULS)
	Nuls CoinType = 8964
	// Zelcash (FLUX)
	Zelcash CoinType = 19167
	// Wanchain (WAN)
	Wanchain CoinType = 5718350
	// Waves (WAVES)
	Waves CoinType = 5741564
	// Smart Chain Legacy (BNB)
	Bsc CoinType = 10000714
	// Smart Chain (BNB)
	Smartchain CoinType = 20000714
	// Polygon (POL)
	Polygon CoinType = 966
	// Rootstock (RBTC)
	Rootstock CoinType = 137
	// THORChain (RUNE)
	Thorchain CoinType = 931
	// Optimism (ETH)
	Optimism CoinType = 10000070
	// Polygon zkEVM (ETH)
	Polygonzkevm CoinType = 10001101
	// Zksync (ETH)
	Zksync CoinType = 10000324
	// Scroll (ETH)
	Scroll CoinType = 534352
	// Arbitrum (ETH)
	Arbitrum CoinType = 10042221
	// Arbitrum Nova (ETH)
	Arbitrumnova CoinType = 10042170
	// ECO Chain (HT)
	Heco CoinType = 10000553
	// Avalanche C-Chain (AVAX)
	Avalanchec CoinType = 10009000
	// xDai (xDAI)
	Xdai CoinType = 10000100
	// Fantom (FTM)
	Fantom CoinType = 10000250
	// CryptoOrg (CRO)
	Cryptoorg CoinType = 394
	// Celo (CELO)
	Celo CoinType = 52752
	// Ronin (RON)
	Ronin CoinType = 10002020
	// Secret (SCRT)
	Secret CoinType = 529
	// Osmosis (OSMO)
	Osmosis CoinType = 10000118
	// eCash (XEC)
	Ecash CoinType = 899
	// IOST (IOST)
	Iost CoinType = 291
	// Cronos Chain (CRO)
	Cronos CoinType = 10000025
	// KavaEvm (KAVA)
	Kavaevm CoinType = 10002222
	// Smart Bitcoin Cash (BCH)
	Smartbch CoinType = 10000145
	// KuCoin Community Chain (KCS)
	Kcc CoinType = 10000321
	// Boba (BOBAETH)
	Boba CoinType = 10000288
	// Metis (METIS)
	Metis CoinType = 10001088
	// Aurora (ETH)
	Aurora CoinType = 1323161554
	// Evmos (EVMOS)
	Evmos CoinType = 10009001
	// NativeEvmos (EVMOS)
	Nativeevmos CoinType = 20009001
	// Moonriver (MOVR)
	Moonriver CoinType = 10001285
	// Moonbeam (GLMR)
	Moonbeam CoinType = 10001284
	// Kaia (KAIA)
	Kaia CoinType = 10008217
	// Meter (MTR)
	Meter CoinType = 18000
	// OKX Chain (OKT)
	Okc CoinType = 996
	// Conflux eSpace (CFX)
	Cfxevm CoinType = 1030
	// Greenfield (BNB)
	Greenfield CoinType = 5600
	// OpBNB (BNB)
	Opbnb CoinType = 204
	// Stratis (STRAX)
	Stratis CoinType = 105105
	// Nebl (NEBL)
	Nebl CoinType = 146
	// Hedera (HBAR)
	Hedera CoinType = 3030
	// Agoric (BLD)
	Agoric CoinType = 564
	// Dydx (DYDX)
	Dydx CoinType = 22000118
	// NativeInjective (INJ)
	Nativeinjective CoinType = 10000060
	// NativeCanto (CANTO)
	Nativecanto CoinType = 10007700
	// NativeZetaChain (ZETA)
	Zetachain CoinType = 10007000
	// Zeta EVM (ZETA)
	Zetaevm CoinType = 20007000
	// TON (TON)
	Ton CoinType = 607
	// Neon (NEON)
	Neon CoinType = 245022934
	// Internet Computer (ICP)
	Internet_computer CoinType = 223
	// Manta Pacific (ETH)
	Manta CoinType = 169
	// Merlin (BTC)
	Merlin CoinType = 4200
	// Lightlink (ETH)
	Lightlink CoinType = 1890
	// Blast (ETH)
	Blast CoinType = 81457
	// BounceBit (BB)
	Bouncebit CoinType = 6001
	// ZkLinkNova (ETH)
	Zklinknova CoinType = 810180
	// Sonic (S)
	Sonic CoinType = 10000146
	// Pactus (PAC)
	Pactus CoinType = 21888
	// Polymesh (POLYX)
	Polymesh CoinType = 595
	// Plasma (XPL)
	Plasma CoinType = 9745
	// Monad (MON)
	Monad CoinType = 10143
	// MegaETH (ETH)
	Megaeth CoinType = 4326
)

// AllCoins returns a slice of all supported coin types
func AllCoins() []CoinType {
	return []CoinType{
		Bitcoin,
		Litecoin,
		Doge,
		Dash,
		Viacoin,
		Groestlcoin,
		Digibyte,
		Monacoin,
		Decred,
		Syscoin,
		Base,
		Linea,
		Mantle,
		Zeneon,
		Ethereum,
		Classic,
		Icon,
		Verge,
		Pivx,
		Zen,
		Aptos,
		Sui,
		Cosmos,
		Stargaze,
		Juno,
		Stride,
		Axelar,
		Crescent,
		Kujira,
		Comdex,
		Neutron,
		Sommelier,
		Fetchai,
		Mars,
		Umee,
		Noble,
		Sei,
		Tia,
		Coreum,
		Quasar,
		Persistence,
		Akash,
		Zcash,
		Firo,
		Komodo,
		Ripple,
		Bitcoincash,
		Stellar,
		Bitcoingold,
		Nano,
		Ravencoin,
		Poa,
		Eos,
		Wax,
		Tron,
		Fio,
		Nimiq,
		Algorand,
		Iotex,
		Iotexevm,
		Nervos,
		Zilliqa,
		Terra,
		Terrav2,
		Polkadot,
		Everscale,
		Near,
		Aion,
		Kusama,
		Acala,
		Acalaevm,
		Aeternity,
		Kava,
		Filecoin,
		Bluzelle,
		Band,
		Theta,
		Tfuelevm,
		Solana,
		Elrond,
		Binance,
		Tbinance,
		Vechain,
		Callisto,
		Neo,
		Viction,
		Bitcoindiamond,
		Thundertoken,
		Harmony,
		Oasis,
		Ontology,
		Tezos,
		Cardano,
		Kin,
		Qtum,
		Nebulas,
		Gochain,
		Nuls,
		Zelcash,
		Wanchain,
		Waves,
		Bsc,
		Smartchain,
		Polygon,
		Rootstock,
		Thorchain,
		Optimism,
		Polygonzkevm,
		Zksync,
		Scroll,
		Arbitrum,
		Arbitrumnova,
		Heco,
		Avalanchec,
		Xdai,
		Fantom,
		Cryptoorg,
		Celo,
		Ronin,
		Secret,
		Osmosis,
		Ecash,
		Iost,
		Cronos,
		Kavaevm,
		Smartbch,
		Kcc,
		Boba,
		Metis,
		Aurora,
		Evmos,
		Nativeevmos,
		Moonriver,
		Moonbeam,
		Kaia,
		Meter,
		Okc,
		Cfxevm,
		Greenfield,
		Opbnb,
		Stratis,
		Nebl,
		Hedera,
		Agoric,
		Dydx,
		Nativeinjective,
		Nativecanto,
		Zetachain,
		Zetaevm,
		Ton,
		Neon,
		Internet_computer,
		Manta,
		Merlin,
		Lightlink,
		Blast,
		Bouncebit,
		Zklinknova,
		Sonic,
		Pactus,
		Polymesh,
		Plasma,
		Monad,
		Megaeth,
	}
}

// CoinByID returns a CoinType by its string ID (e.g., "bitcoin", "ethereum")
func CoinByID(id string) (CoinType, bool) {
	switch id {
	case "bitcoin":
		return Bitcoin, true
	case "litecoin":
		return Litecoin, true
	case "doge":
		return Doge, true
	case "dash":
		return Dash, true
	case "viacoin":
		return Viacoin, true
	case "groestlcoin":
		return Groestlcoin, true
	case "digibyte":
		return Digibyte, true
	case "monacoin":
		return Monacoin, true
	case "decred":
		return Decred, true
	case "syscoin":
		return Syscoin, true
	case "base":
		return Base, true
	case "linea":
		return Linea, true
	case "mantle":
		return Mantle, true
	case "zeneon":
		return Zeneon, true
	case "ethereum":
		return Ethereum, true
	case "classic":
		return Classic, true
	case "icon":
		return Icon, true
	case "verge":
		return Verge, true
	case "pivx":
		return Pivx, true
	case "zen":
		return Zen, true
	case "aptos":
		return Aptos, true
	case "sui":
		return Sui, true
	case "cosmos":
		return Cosmos, true
	case "stargaze":
		return Stargaze, true
	case "juno":
		return Juno, true
	case "stride":
		return Stride, true
	case "axelar":
		return Axelar, true
	case "crescent":
		return Crescent, true
	case "kujira":
		return Kujira, true
	case "comdex":
		return Comdex, true
	case "neutron":
		return Neutron, true
	case "sommelier":
		return Sommelier, true
	case "fetchai":
		return Fetchai, true
	case "mars":
		return Mars, true
	case "umee":
		return Umee, true
	case "noble":
		return Noble, true
	case "sei":
		return Sei, true
	case "tia":
		return Tia, true
	case "coreum":
		return Coreum, true
	case "quasar":
		return Quasar, true
	case "persistence":
		return Persistence, true
	case "akash":
		return Akash, true
	case "zcash":
		return Zcash, true
	case "firo":
		return Firo, true
	case "komodo":
		return Komodo, true
	case "ripple":
		return Ripple, true
	case "bitcoincash":
		return Bitcoincash, true
	case "stellar":
		return Stellar, true
	case "bitcoingold":
		return Bitcoingold, true
	case "nano":
		return Nano, true
	case "ravencoin":
		return Ravencoin, true
	case "poa":
		return Poa, true
	case "eos":
		return Eos, true
	case "wax":
		return Wax, true
	case "tron":
		return Tron, true
	case "fio":
		return Fio, true
	case "nimiq":
		return Nimiq, true
	case "algorand":
		return Algorand, true
	case "iotex":
		return Iotex, true
	case "iotexevm":
		return Iotexevm, true
	case "nervos":
		return Nervos, true
	case "zilliqa":
		return Zilliqa, true
	case "terra":
		return Terra, true
	case "terrav2":
		return Terrav2, true
	case "polkadot":
		return Polkadot, true
	case "everscale":
		return Everscale, true
	case "near":
		return Near, true
	case "aion":
		return Aion, true
	case "kusama":
		return Kusama, true
	case "acala":
		return Acala, true
	case "acalaevm":
		return Acalaevm, true
	case "aeternity":
		return Aeternity, true
	case "kava":
		return Kava, true
	case "filecoin":
		return Filecoin, true
	case "bluzelle":
		return Bluzelle, true
	case "band":
		return Band, true
	case "theta":
		return Theta, true
	case "tfuelevm":
		return Tfuelevm, true
	case "solana":
		return Solana, true
	case "elrond":
		return Elrond, true
	case "binance":
		return Binance, true
	case "tbinance":
		return Tbinance, true
	case "vechain":
		return Vechain, true
	case "callisto":
		return Callisto, true
	case "neo":
		return Neo, true
	case "viction":
		return Viction, true
	case "bitcoindiamond":
		return Bitcoindiamond, true
	case "thundertoken":
		return Thundertoken, true
	case "harmony":
		return Harmony, true
	case "oasis":
		return Oasis, true
	case "ontology":
		return Ontology, true
	case "tezos":
		return Tezos, true
	case "cardano":
		return Cardano, true
	case "kin":
		return Kin, true
	case "qtum":
		return Qtum, true
	case "nebulas":
		return Nebulas, true
	case "gochain":
		return Gochain, true
	case "nuls":
		return Nuls, true
	case "zelcash":
		return Zelcash, true
	case "wanchain":
		return Wanchain, true
	case "waves":
		return Waves, true
	case "bsc":
		return Bsc, true
	case "smartchain":
		return Smartchain, true
	case "polygon":
		return Polygon, true
	case "rootstock":
		return Rootstock, true
	case "thorchain":
		return Thorchain, true
	case "optimism":
		return Optimism, true
	case "polygonzkevm":
		return Polygonzkevm, true
	case "zksync":
		return Zksync, true
	case "scroll":
		return Scroll, true
	case "arbitrum":
		return Arbitrum, true
	case "arbitrumnova":
		return Arbitrumnova, true
	case "heco":
		return Heco, true
	case "avalanchec":
		return Avalanchec, true
	case "xdai":
		return Xdai, true
	case "fantom":
		return Fantom, true
	case "cryptoorg":
		return Cryptoorg, true
	case "celo":
		return Celo, true
	case "ronin":
		return Ronin, true
	case "secret":
		return Secret, true
	case "osmosis":
		return Osmosis, true
	case "ecash":
		return Ecash, true
	case "iost":
		return Iost, true
	case "cronos":
		return Cronos, true
	case "kavaevm":
		return Kavaevm, true
	case "smartbch":
		return Smartbch, true
	case "kcc":
		return Kcc, true
	case "boba":
		return Boba, true
	case "metis":
		return Metis, true
	case "aurora":
		return Aurora, true
	case "evmos":
		return Evmos, true
	case "nativeevmos":
		return Nativeevmos, true
	case "moonriver":
		return Moonriver, true
	case "moonbeam":
		return Moonbeam, true
	case "kaia":
		return Kaia, true
	case "meter":
		return Meter, true
	case "okc":
		return Okc, true
	case "cfxevm":
		return Cfxevm, true
	case "greenfield":
		return Greenfield, true
	case "opbnb":
		return Opbnb, true
	case "stratis":
		return Stratis, true
	case "Nebl":
		return Nebl, true
	case "hedera":
		return Hedera, true
	case "agoric":
		return Agoric, true
	case "dydx":
		return Dydx, true
	case "nativeinjective":
		return Nativeinjective, true
	case "nativecanto":
		return Nativecanto, true
	case "zetachain":
		return Zetachain, true
	case "zetaevm":
		return Zetaevm, true
	case "ton":
		return Ton, true
	case "neon":
		return Neon, true
	case "internet_computer":
		return Internet_computer, true
	case "manta":
		return Manta, true
	case "merlin":
		return Merlin, true
	case "lightlink":
		return Lightlink, true
	case "blast":
		return Blast, true
	case "bouncebit":
		return Bouncebit, true
	case "zklinknova":
		return Zklinknova, true
	case "sonic":
		return Sonic, true
	case "pactus":
		return Pactus, true
	case "polymesh":
		return Polymesh, true
	case "plasma":
		return Plasma, true
	case "monad":
		return Monad, true
	case "megaeth":
		return Megaeth, true
	default:
		return 0, false
	}
}

// CoinBySymbol returns a CoinType by its symbol (e.g., "BTC", "ETH")
// Note: Some symbols map to multiple coins. Returns the first match.
func CoinBySymbol(symbol string) (CoinType, bool) {
	switch symbol {
	case "BTC":
		return Bitcoin, true
	case "LTC":
		return Litecoin, true
	case "DOGE":
		return Doge, true
	case "DASH":
		return Dash, true
	case "VIA":
		return Viacoin, true
	case "GRS":
		return Groestlcoin, true
	case "DGB":
		return Digibyte, true
	case "MONA":
		return Monacoin, true
	case "DCR":
		return Decred, true
	case "SYS":
		return Syscoin, true
	case "ETH":
		return Base, true
	case "MNT":
		return Mantle, true
	case "ZEN":
		return Zeneon, true
	case "ETC":
		return Classic, true
	case "ICX":
		return Icon, true
	case "XVG":
		return Verge, true
	case "PIVX":
		return Pivx, true
	case "APT":
		return Aptos, true
	case "SUI":
		return Sui, true
	case "ATOM":
		return Cosmos, true
	case "STARS":
		return Stargaze, true
	case "JUNO":
		return Juno, true
	case "STRD":
		return Stride, true
	case "AXL":
		return Axelar, true
	case "CRE":
		return Crescent, true
	case "KUJI":
		return Kujira, true
	case "CMDX":
		return Comdex, true
	case "NTRN":
		return Neutron, true
	case "SOMM":
		return Sommelier, true
	case "FET":
		return Fetchai, true
	case "MARS":
		return Mars, true
	case "UMEE":
		return Umee, true
	case "USDC":
		return Noble, true
	case "SEI":
		return Sei, true
	case "TIA":
		return Tia, true
	case "CORE":
		return Coreum, true
	case "QSR":
		return Quasar, true
	case "XPRT":
		return Persistence, true
	case "AKT":
		return Akash, true
	case "ZEC":
		return Zcash, true
	case "FIRO":
		return Firo, true
	case "KMD":
		return Komodo, true
	case "XRP":
		return Ripple, true
	case "BCH":
		return Bitcoincash, true
	case "XLM":
		return Stellar, true
	case "BTG":
		return Bitcoingold, true
	case "XNO":
		return Nano, true
	case "RVN":
		return Ravencoin, true
	case "POA":
		return Poa, true
	case "EOS":
		return Eos, true
	case "WAXP":
		return Wax, true
	case "TRX":
		return Tron, true
	case "FIO":
		return Fio, true
	case "NIM":
		return Nimiq, true
	case "ALGO":
		return Algorand, true
	case "IOTX":
		return Iotex, true
	case "CKB":
		return Nervos, true
	case "ZIL":
		return Zilliqa, true
	case "LUNC":
		return Terra, true
	case "LUNA":
		return Terrav2, true
	case "DOT":
		return Polkadot, true
	case "EVER":
		return Everscale, true
	case "NEAR":
		return Near, true
	case "AION":
		return Aion, true
	case "KSM":
		return Kusama, true
	case "ACA":
		return Acala, true
	case "AE":
		return Aeternity, true
	case "KAVA":
		return Kava, true
	case "FIL":
		return Filecoin, true
	case "BLZ":
		return Bluzelle, true
	case "BAND":
		return Band, true
	case "THETA":
		return Theta, true
	case "TFUEL":
		return Tfuelevm, true
	case "SOL":
		return Solana, true
	case "eGLD":
		return Elrond, true
	case "BNB":
		return Binance, true
	case "VET":
		return Vechain, true
	case "CLO":
		return Callisto, true
	case "NEO":
		return Neo, true
	case "VIC":
		return Viction, true
	case "BCD":
		return Bitcoindiamond, true
	case "TT":
		return Thundertoken, true
	case "ONE":
		return Harmony, true
	case "ROSE":
		return Oasis, true
	case "ONT":
		return Ontology, true
	case "XTZ":
		return Tezos, true
	case "ADA":
		return Cardano, true
	case "KIN":
		return Kin, true
	case "QTUM":
		return Qtum, true
	case "NAS":
		return Nebulas, true
	case "GO":
		return Gochain, true
	case "NULS":
		return Nuls, true
	case "FLUX":
		return Zelcash, true
	case "WAN":
		return Wanchain, true
	case "WAVES":
		return Waves, true
	case "POL":
		return Polygon, true
	case "RBTC":
		return Rootstock, true
	case "RUNE":
		return Thorchain, true
	case "HT":
		return Heco, true
	case "AVAX":
		return Avalanchec, true
	case "xDAI":
		return Xdai, true
	case "FTM":
		return Fantom, true
	case "CRO":
		return Cryptoorg, true
	case "CELO":
		return Celo, true
	case "RON":
		return Ronin, true
	case "SCRT":
		return Secret, true
	case "OSMO":
		return Osmosis, true
	case "XEC":
		return Ecash, true
	case "IOST":
		return Iost, true
	case "KCS":
		return Kcc, true
	case "BOBAETH":
		return Boba, true
	case "METIS":
		return Metis, true
	case "EVMOS":
		return Evmos, true
	case "MOVR":
		return Moonriver, true
	case "GLMR":
		return Moonbeam, true
	case "KAIA":
		return Kaia, true
	case "MTR":
		return Meter, true
	case "OKT":
		return Okc, true
	case "CFX":
		return Cfxevm, true
	case "STRAX":
		return Stratis, true
	case "NEBL":
		return Nebl, true
	case "HBAR":
		return Hedera, true
	case "BLD":
		return Agoric, true
	case "DYDX":
		return Dydx, true
	case "INJ":
		return Nativeinjective, true
	case "CANTO":
		return Nativecanto, true
	case "ZETA":
		return Zetachain, true
	case "TON":
		return Ton, true
	case "NEON":
		return Neon, true
	case "ICP":
		return Internet_computer, true
	case "BB":
		return Bouncebit, true
	case "S":
		return Sonic, true
	case "PAC":
		return Pactus, true
	case "POLYX":
		return Polymesh, true
	case "XPL":
		return Plasma, true
	case "MON":
		return Monad, true
	default:
		return 0, false
	}
}
